name: CI

on:
  push:
    branches: [ main ]

 jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          sudo bash debian-xfce.sh
          sudo mkdir -p /output
          sudo mv debian-xfce.iso /output/debian-xfce.iso


      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "main"
          prerelease: false
          title: "Daily build"
          files: |
            /output/*
